FROM rust:latest AS builder
ENV APP frontend
RUN apt update && apt install lld clang -y
RUN cargo install trunk
RUN rustup target add wasm32-unknown-unknown
# ENV 
EXPOSE 8080
ENV TRUNK_SERVE_ADDRESS 0.0.0.0
ENV TRUNK_SERVE_PORT 8080
WORKDIR /app
COPY . .
CMD ["trunk", "serve"]
