name: quiz-web-application-prod
services:
  # -- Frontend / NGINX
  leptosfrontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # NGINX listens on 80
      - 80:80
      - 443:443
    volumes:
      #   - ./ssl:/ect/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - actixbackend
      - certbot
  # -- Certbot to create Challenge Files
  certbot:
    image: certbot/certbot:latest
    # volumes same as NGINX to communicate
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos
  # -- Backend
  actixbackend:
    # image: quiz-backend
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    depends_on:
      - surrealdb
  # -- DataBase
  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      # May require giving privileges to source directory
      - type: bind
        source: /var/lib/surrealquizdata
        target: /data
    ports:
      - 8001:8000
    # Set Environment Variables for Security
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:data/mydatabase.db
# volumes:
#   surrealdata:
