name: quiz-web-application-prod
services:
  # -- Frontend / NGINX
  leptosfrontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - actixbackend
      # REMINDER, RUN CERTBOT TO GENERATE CERTIFICATES
      # - certbot
  # -- Certbot to create Challenge Files
  certbot:
    profiles: ["certbot"]
    image: certbot/certbot:latest
    # volumes same as NGINX to communicate
    environment:
      # Doesn't do much but serves as reminder to set this variable!
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
      # Below is a line for reading logs! Handy for debugging
      # - ./certbot/log:/var/log/letsencrypt/:rw
    command: >
      certonly --webroot -w /var/www/certbot  --force-renewal --email ${CERTBOT_EMAIL:-kevin.sullivan@example.com} -d kevsquizappiu.com --agree-tos

  # -- Backend
  actixbackend:
    # image: quiz-backend
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    environment:
      - QUIZAPP_DATABASE__USERNAME=${DB_USER:-user}
      - QUIZAPP_DATABASE__PASSWORD=${DB_PASSWORD}
      - QUIZAPP_APPLICATION__HMAC_SECRET=${QUIZAPP_APPLICATION__HMAC_SECRET}
    ports:
      - 8002:8002
    depends_on:
      - surrealdb
  # -- DataBase
  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      # May require giving privileges to source directory
      - type: bind
        source: /var/lib/surrealquizdata
        target: /data
    ports:
      - 8000:8000
    # Set Environment Variables for Security
    environment:
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint:
      - /surreal
      - start
      - --log
      - trace
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:data/mydatabase.db
# volumes:
#   surrealdata:
