name: quiz-web-application
services:
  backend:
    # image: quiz-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      # network: host
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      # Named Volume - Might change to Bind-Mount
      - type: bind
        source: /var/lib/surrealquizdata
        target: /data
    ports:
      - 8001:8000
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:data/mydatabase.db
# volumes:
#   surrealdata:
