name: quiz-web-application
services:
  backend:
    # image: quiz-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      # network: host
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
