FROM alpine:latest

RUN apk add --no-cache openssl

WORKDIR /certs

# Generate self-signed certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout privkey.pem -out fullchain.pem \
  -subj "/C=IE/ST=Cork/L=Cork/O=IU/CN=quiztestapp.io"

CMD ["echo", "OpenSSL Certificates Generated."]
