# FROM rust:1.78-slim-bookworm
#
# WORKDIR /app
# RUN apt update && apt install lld clang -y
# COPY . .
# EXPOSE 8080
# # RUN cargo build
#
# # ENV APP_ENVIRONMENT development
# # ENTRYPOINT ["./target/debug/backend"]
# # CMD ["./target/debug/backend"]
# CMD ["cargo", "run"]


FROM rust:latest AS builder
RUN apt update && apt install lld clang -y
WORKDIR /app
RUN cargo init . --vcs none
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --bin backend
# ---
COPY . .
RUN cargo build --bin backend
EXPOSE 8000
ENV APP_ENVIRONMENT local
ENV QUIZAPP_APPLICATION__HOST 0.0.0.0
CMD ["./target/debug/backend"]
# CMD ["cargo", "run"]

# FROM debian:bookworm-slim AS runtime
# # RUN apk add --no-cache libc6-compat
# COPY --from=builder /app/target/debug/backend /app
# EXPOSE 8080
# WORKDIR /app
# CMD ["backend"]
