[package]
name = "surrealize_macro"
edition = "2021"
version.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
surrealdb = { version = "1.5"  }
syn = { version = "2.0.68", features = ["full"] }
tokio = { version = "1" }
